### ISSUE TITLE
关于在next主题下的应用

### ISSUE THREAD

**Issue by zdaiot** [zthxxx/hexo-directory-category#5]
您好，我之前搭建博客使用的是next主题，感觉更改主题有点麻烦。想直接使用您的这个插件，但是现在出现的问题是：安装并配置您的这个插件后，设置参数为
```
auto_dir_categorize:
	enable: true  # options:true, false; default is true
	force: true
```
会导致出现两级目录，例如`file: ./_posts/Linux/Vim.md`，`categories: [Linux]`，那么生成的html目录为`Linux/Linux`。若`categories: [...]`，生成的html目录为`uncategorized/Linux`。
请问我需要更改什么文件去修复这个问题？谢谢~

**Comment by zthxxx** [comment]
复现仓库是这个吗  https://github.com/zdaiot/zdaiot.github.io

**Comment by zthxxx** [comment]
先说结论，图见下；

插件工作是正常的， 问题出在你站点配置的 [_config.yam](https://github.com/zdaiot/zdaiot.github.io/blob/f02de893711ab0a2c5daeee6f6b7d987c9edd707/_config.yml#L18) 中的永久链接设置上，

你自己加了重复的 category到 path 上，

正确的写法是只放 title 和固定的 prefix 就行， 文件[参见此处](https://github.com/zthxxx/Wiki-site/blob/writing/_config.yml#L17)

```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://wiki.zthxxx.me
root: /
permalink: wiki/:title/
permalink_defaults:
```


![image](https://user-images.githubusercontent.com/15135943/58372609-b7404880-7f52-11e9-866a-4c691b2a369e.png)

![image](https://user-images.githubusercontent.com/15135943/58372617-d5a64400-7f52-11e9-953e-4d5549a4fbbb.png)

![image](https://user-images.githubusercontent.com/15135943/58372859-c88b5400-7f56-11e9-9622-135c4848b5b9.png)
